name: Stable Release

on:
  pull_request:
    types: [closed]
    branches: [stable]

permissions:
  contents: write

jobs:
  release:
    name: Create Stable Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: stable
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-targets: false
      - uses: knope-dev/action@v2.1.2

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cargo run --package xtask -- versioning release-stable
